# Generated by Django 4.2.6 on 2023-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('letter', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('gpa', models.FloatField()),
            ],
            options={
                'db_table': 'da_grade',
            },
        ),
        migrations.CreateModel(
            name='UGMajor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'da_ug_major',
            },
        ),
    ]
