# Generated by Django 4.2.6 on 2023-12-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passing_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.grade')),
            ],
            options={
                'db_table': 'da_course',
            },
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'da_subject_code',
            },
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'da_subject_level',
            },
        ),
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fixed', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.course')),
                ('levels', models.ManyToManyField(to='DegreeAudit.subjectlevel')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.subjectcode')),
            ],
            options={
                'db_table': 'da_subject_choice',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('credits', models.IntegerField()),
                ('is_elective', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.ugmajor')),
            ],
            options={
                'db_table': 'da_section',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.section'),
        ),
    ]
