# Generated by Django 4.2.6 on 2023-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0002_course_subjectcode_subjectlevel_subjectchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
