# Generated by Django 4.2.6 on 2023-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0010_passstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.section')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.studentinfo')),
            ],
            options={
                'db_table': 'da_section_info',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=500)),
                ('subject_credit', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.course')),
                ('pass_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.passstatus')),
                ('section_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.sectioninfo')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.subjectcode')),
                ('subject_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.grade')),
                ('subject_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DegreeAudit.subjectlevel')),
            ],
            options={
                'db_table': 'da_course_info',
            },
        ),
    ]
