# Generated by Django 4.2.6 on 2023-12-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DegreeAudit', '0011_sectioninfo_courseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.course'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='pass_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.passstatus'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='section_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.sectioninfo'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectcode'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='subject_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.grade'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='subject_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectlevel'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.section'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.studentinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.ugmajor'),
        ),
    ]
