# Generated by Django 4.2.6 on 2023-12-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0013_alter_courseinfo_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='pass_status',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_credit',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_grade',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_level',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_name',
        ),
        migrations.CreateModel(
            name='SubjectChoiceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=500)),
                ('subject_credit', models.IntegerField()),
                ('course_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.courseinfo')),
                ('pass_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.passstatus')),
                ('section_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.sectioninfo')),
                ('subject_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectcode')),
                ('subject_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.grade')),
                ('subject_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectlevel')),
            ],
            options={
                'db_table': 'da_subject_choice_info',
            },
        ),
    ]
