# Generated by Django 4.2.6 on 2023-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0014_remove_courseinfo_pass_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='pass_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_grade',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_level',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PassStatus',
        ),
    ]
