# Generated by Django 4.2.6 on 2023-12-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0015_alter_subjectchoiceinfo_pass_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassStatus',
            fields=[
                ('status', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'da_pass_status',
            },
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectcode'),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.grade'),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.subjectlevel'),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='pass_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DegreeAudit.passstatus'),
        ),
    ]
