# Generated by Django 4.2.6 on 2023-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0016_passstatus_alter_subjectchoiceinfo_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectchoiceinfo',
            name='subject_level',
            field=models.CharField(max_length=100),
        ),
    ]
