# Generated by Django 4.2.6 on 2023-12-14 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0017_alter_subjectchoiceinfo_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 13, 37, 54, 854781)),
        ),
    ]
