# Generated by Django 4.2.6 on 2023-12-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0018_studentinfo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
    ]
