# Generated by Django 4.2.6 on 2023-12-14 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0019_alter_studentinfo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
