# Generated by Django 4.2.6 on 2023-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0020_alter_studentinfo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
