# Generated by Django 4.2.6 on 2023-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0021_section_file_section_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='file',
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
