# Generated by Django 4.2.6 on 2023-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DegreeAudit', '0022_remove_section_file_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfo',
            name='need_credits',
            field=models.IntegerField(default=0),
        ),
    ]
